### ISSUE TITLE
Crash of the app (dropdown add and modify fragment)

### ISSUE THREAD

**Issue by SchifName** [Apocalixs-Nick/NewMyCar#1]
Whenever you click on a drop down list and press ok, when you haven't chosen any option, the app will crash. 
(this bug is present not only in the edit car fragment but also in the add new car fragment )
<img src="https://user-images.githubusercontent.com/110109311/208935200-b59c07ab-bfcf-4d2e-976e-fa580278cda2.jpg" width="200" height="400" />       <img src="https://user-images.githubusercontent.com/110109311/208935981-15c1bd2d-9f92-43a8-a414-a347820cb487.jpg" width="200" height="400" /> 
Here's another screenshot to prove it, it doesn't show up every time, it was hard to find and that's why I'm sharing it just now.
<img src="https://user-images.githubusercontent.com/110109311/208938929-af0d62df-00ac-4162-a6a3-68970b31a704.png" width="400" height="100" />

**Comment by SchifName** [comment]
Here's another screenshot to prove it, it doesn't show up every time, it was hard to find and that's why I'm sharing it here.
<img src="https://user-images.githubusercontent.com/110109311/208938929-af0d62df-00ac-4162-a6a3-68970b31a704.png" width="400" height="100" />

**Comment by Apocalixs-Nick** [comment]
The bug you reported has been fixed, in release there is the updated apk
