### ISSUE TITLE
Car details can have value 0 or infinite characters

### ISSUE THREAD

**Issue by SchifName** [Apocalixs-Nick/NewMyCar#2]
ISSUE 1

These fields shouldn't be allowed to have value of 0.

<img src="https://user-images.githubusercontent.com/110109311/208942910-8e8db32a-84d8-4272-81ac-dd45aeafb606.png" width="200" height="400" />

ISSUE 2

In this case the color field shouldn't show so many characters. Because it can cause UI issues as shown.

<img src="https://user-images.githubusercontent.com/110109311/208942906-39474620-986e-41b2-ba21-3d1ab80acf5d.png" width="250" height="400" />

**Comment by Apocalixs-Nick** [comment]
I resolved bug with adding min e max value por power, door, year and seat text input, with snackbar alert and add longClickable on false.
This is the link for new apk:
https://github.com/Apocalixs-Nick/NewMyCar/releases/download/1.0.3/app-debug.apk
